services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DISABLE_CLUSTER_API: "true"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
