apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: {{ include "nrdc-poc.namespace" . }}
  labels:
    app: backend
    {{- include "nrdc-poc.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nrdc-poc.name" . }}-backend-reader
  labels:
    {{- include "nrdc-poc.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "namespaces", "services"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nrdc-poc.name" . }}-backend-reader
  labels:
    {{- include "nrdc-poc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nrdc-poc.name" . }}-backend-reader
subjects:
  - kind: ServiceAccount
    name: backend
    namespace: {{ include "nrdc-poc.namespace" . }}
