apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ include "nrdc-poc.namespace" . }}
  labels:
    app: backend
    {{- include "nrdc-poc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
